version: "3.8"

services:
  app:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    container_name: middleware-app
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/imageUploadDB # MongoDB service hostname
    depends_on:
      - mongo # Ensure MongoDB is started before the app
    volumes:
      - uploads:/app/uploads
      - emojis:/app/emojis
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

volumes:
  uploads: # Volume for uploaded images (shared between middleware and vision application)
  emojis: # Volume for generated (shared between middleware and stable diffsion application)
  mongo-data: # Volume for persist MongoDB data

networks:
  app-network: # Shared network for communication between services
