version: "3.8"

services:
  app:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    container_name: middleware-app
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/imageUploadDB # MongoDB service hostname
    depends_on:
      - mongo # Ensure MongoDB is started before the app
    networks:
      - app-network

  mongo:
    image: mongo # Use the official MongoDB image
    container_name: mongodb
    ports:
      - "27017:27017" # Map MongoDB port to host
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

volumes:
  mongo-data: # Volume for MongoDB data

networks:
  app-network: # Shared network for communication between services
